name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all -- --check
      - name: check
        run: cargo check --all-targets --locked
      - name: clippy
        run: cargo clippy --all-targets --locked -- -D warnings
      - name: test
        run: cargo test --all --locked

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.85.0
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: check MSRV
        run: cargo check --all-targets --locked
      - name: test MSRV
        run: cargo test --all --locked
